from flask import Flask, request, redirect, url_for, session, render_template_string
import os
import psycopg
from psycopg.rows import dict_row
import random
from functools import wraps

app = Flask(__name__)

# ==========================================
# CONFIGURACIÓN
# ==========================================

app.secret_key = "clave-demo-sorteoweb"

CONTRASENA_ADMIN = "1234"

DATABASE_URL = os.environ.get("DATABASE_URL")


# ==========================================
# BASE DE DATOS
# ==========================================

def conectar():

    if not DATABASE_URL:
        raise RuntimeError(
            "Falta la variable de entorno DATABASE_URL. "
            "Configúrala en Render para conectar con Supabase."
        )

    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def crear_base_datos():

    conexion = conectar()
    cursor = conexion.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS sorteos (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre TEXT NOT NULL,
            premio TEXT NOT NULL,
            descripcion TEXT,
            fecha TEXT,
            activo INTEGER DEFAULT 1,
            premio_imagen TEXT
        )
    """)

    # Compatibilidad con la tabla que ya existe en Supabase.
    cursor.execute("ALTER TABLE sorteos ADD COLUMN IF NOT EXISTS premio_imagen TEXT")

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS participantes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre TEXT NOT NULL,
            correo TEXT NOT NULL,
            telefono TEXT NOT NULL,
            sorteo_id BIGINT REFERENCES sorteos(id)
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS ganadores (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sorteo_id BIGINT UNIQUE NOT NULL REFERENCES sorteos(id) ON DELETE CASCADE,
            participante_id BIGINT NOT NULL REFERENCES participantes(id) ON DELETE RESTRICT,
            fecha TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        )
    """)

    cursor.execute("SELECT COUNT(*) AS cantidad FROM sorteos")
    cantidad = cursor.fetchone()["cantidad"]

    if cantidad == 0:
        cursor.execute("""
            INSERT INTO sorteos
            (nombre, premio, descripcion, fecha, activo, premio_imagen)
            VALUES (%s, %s, %s, %s, %s, %s)
        """, (
            "Gran Sorteo Promocional",
            "Premio sorpresa",
            "Participa gratuitamente en nuestro sorteo promocional.",
            "2026-12-31",
            1,
            None
        ))

    conexion.commit()
    cursor.close()
    conexion.close()


# ==========================================
# PROTECCIÓN DEL ADMINISTRADOR
# ==========================================

def requiere_admin(funcion):

    @wraps(funcion)
    def protegida(*args, **kwargs):

        if not session.get("admin"):
            return redirect(url_for("login"))

        return funcion(*args, **kwargs)

    return protegida


# ==========================================
# PÁGINA PRINCIPAL
# ==========================================

@app.route("/")
def inicio():

    conexion = conectar()

    sorteos = conexion.execute("""
        SELECT *
        FROM sorteos
        WHERE activo = 1
        ORDER BY id DESC
    """).fetchall()

    ganadores = conexion.execute("""
        SELECT
            g.id,
            g.fecha,
            s.nombre AS sorteo_nombre,
            s.premio,
            p.nombre AS ganador_nombre,
            p.id AS numero_ganador
        FROM ganadores g
        JOIN sorteos s ON s.id = g.sorteo_id
        JOIN participantes p ON p.id = g.participante_id
        ORDER BY g.id DESC
        LIMIT 6
    """).fetchall()

    conexion.close()

    html = """
    <!DOCTYPE html>
    <html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="theme-color" content="#0d0d0d">
        <title>TA PREMIA'O | Sorteos promocionales</title>
        <style>
            :root {
                --negro: #090909;
                --negro-2: #151515;
                --dorado: #c9933b;
                --dorado-claro: #f0c56b;
                --crema: #fffaf0;
                --blanco: #ffffff;
                --gris: #6f6b63;
                --borde: rgba(201,147,59,.25);
            }
            * { box-sizing: border-box; }
            html { scroll-behavior: smooth; }
            body {
                margin: 0;
                font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
                color: var(--negro);
                background:
                    radial-gradient(circle at 10% 5%, rgba(240,197,107,.18), transparent 25%),
                    radial-gradient(circle at 90% 20%, rgba(201,147,59,.12), transparent 30%),
                    linear-gradient(180deg, #090909 0%, #11100e 28%, #f7f2e9 72%, #fffaf0 100%);
                overflow-x: hidden;
            }
            a { color: inherit; }
            .topbar {
                position: sticky;
                top: 0;
                z-index: 20;
                backdrop-filter: blur(18px);
                background: rgba(9,9,9,.88);
                border-bottom: 1px solid rgba(240,197,107,.14);
            }
            .nav {
                max-width: 1180px;
                margin: auto;
                padding: 13px 22px;
                display: flex;
                align-items: center;
                justify-content: space-between;
                gap: 20px;
            }
            .brand {
                display: flex;
                align-items: center;
                gap: 11px;
                text-decoration: none;
                color: #fff;
                font-weight: 900;
                letter-spacing: -.5px;
            }
            .brand img {
                width: 56px;
                height: 56px;
                object-fit: contain;
                border-radius: 50%;
            }
            .brand-name { font-size: 22px; }
            .brand-name span { color: var(--dorado-claro); }
            .nav-links {
                display: flex;
                align-items: center;
                gap: 22px;
                color: rgba(255,255,255,.82);
                font-size: 13px;
                font-weight: 800;
            }
            .nav-links a { text-decoration: none; }
            .nav-links a:hover { color: var(--dorado-claro); }
            .instagram {
                text-decoration: none;
                color: #17120a;
                background: linear-gradient(135deg, #f4cf7c, #b87924);
                padding: 10px 15px;
                border-radius: 999px;
                font-size: 12px;
                font-weight: 900;
                box-shadow: 0 7px 20px rgba(201,147,59,.22);
            }
            .wrap { max-width: 1180px; margin: auto; padding: 0 22px 60px; }
            .hero {
                margin-top: 28px;
                min-height: 540px;
                display: grid;
                grid-template-columns: 1.05fr .95fr;
                gap: 30px;
                align-items: center;
                padding: 56px;
                border: 1px solid rgba(240,197,107,.25);
                border-radius: 34px;
                background:
                    radial-gradient(circle at 80% 20%, rgba(240,197,107,.16), transparent 35%),
                    linear-gradient(135deg, rgba(255,255,255,.07), rgba(255,255,255,.02));
                box-shadow: 0 35px 80px rgba(0,0,0,.35);
                overflow: hidden;
                color: white;
            }
            .eyebrow {
                display: inline-flex;
                padding: 8px 13px;
                border: 1px solid rgba(240,197,107,.35);
                border-radius: 999px;
                color: var(--dorado-claro);
                background: rgba(201,147,59,.08);
                font-size: 12px;
                font-weight: 900;
                letter-spacing: .7px;
            }
            .hero h1 {
                margin: 18px 0 16px;
                max-width: 720px;
                font-size: clamp(42px, 6vw, 76px);
                line-height: .98;
                letter-spacing: -3px;
            }
            .hero h1 span { color: var(--dorado-claro); }
            .hero p {
                max-width: 650px;
                margin: 0;
                color: rgba(255,255,255,.72);
                font-size: 17px;
                line-height: 1.75;
            }
            .hero-actions { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 27px; }
            .btn-primary, .btn-secondary {
                display: inline-flex;
                align-items: center;
                justify-content: center;
                padding: 14px 20px;
                border-radius: 13px;
                text-decoration: none;
                font-weight: 900;
                transition: .2s ease;
            }
            .btn-primary {
                color: #17120a;
                background: linear-gradient(135deg, #f2cc73, #b97a27);
                box-shadow: 0 14px 30px rgba(201,147,59,.25);
            }
            .btn-secondary { color: white; border: 1px solid rgba(255,255,255,.18); background: rgba(255,255,255,.05); }
            .btn-primary:hover, .btn-secondary:hover { transform: translateY(-2px); }
            .hero-logo {
                display: flex;
                justify-content: center;
                align-items: center;
                position: relative;
            }
            .hero-logo:before {
                content: "";
                position: absolute;
                width: 360px;
                height: 360px;
                border-radius: 50%;
                border: 1px solid rgba(240,197,107,.18);
                box-shadow: 0 0 80px rgba(201,147,59,.12);
            }
            .hero-logo img {
                position: relative;
                width: min(390px, 78vw);
                height: auto;
                border-radius: 50%;
                box-shadow: 0 30px 65px rgba(0,0,0,.38);
            }
            .section { margin-top: 58px; }
            .section-head { display: flex; justify-content: space-between; align-items: end; gap: 20px; margin-bottom: 18px; }
            .section-kicker { color: var(--dorado); font-size: 12px; font-weight: 900; letter-spacing: 1.4px; text-transform: uppercase; }
            .section h2 { margin: 5px 0 0; font-size: clamp(28px, 4vw, 42px); letter-spacing: -1.5px; }
            .section-intro { margin: 0; color: var(--gris); line-height: 1.6; }
            .sorteos { display: grid; gap: 22px; }
            .sorteo-card {
                position: relative;
                display: grid;
                grid-template-columns: 1fr 300px;
                gap: 26px;
                padding: 30px;
                border: 1px solid var(--borde);
                border-radius: 25px;
                background: rgba(255,255,255,.94);
                box-shadow: 0 18px 50px rgba(0,0,0,.10);
                overflow: hidden;
            }
            .sorteo-card:before { content: ""; position: absolute; top: 0; left: 0; right: 0; height: 5px; background: linear-gradient(90deg, #a86e1d, #f0c56b, #a86e1d); }
            .card-head { display: flex; align-items: flex-start; justify-content: space-between; gap: 14px; }
            .card-head h3 { margin: 0; font-size: 28px; }
            .active { white-space: nowrap; color: #256a3e; background: #eaf7ee; padding: 7px 10px; border-radius: 999px; font-size: 11px; font-weight: 900; }
            .prize-name { display: inline-block; margin: 15px 0 12px; color: #8d5e16; font-size: 22px; font-weight: 900; }
            .description { color: #69645b; line-height: 1.7; margin: 0; }
            .details { display: flex; flex-wrap: wrap; gap: 9px; margin-top: 18px; }
            .detail { padding: 9px 11px; border-radius: 10px; background: #f8f4eb; color: #625d55; font-size: 13px; }
            .prize-visual {
                min-height: 220px;
                border-radius: 20px;
                overflow: hidden;
                display: flex;
                align-items: center;
                justify-content: center;
                background: linear-gradient(145deg, #181818, #30271a);
                border: 1px solid rgba(201,147,59,.28);
            }
            .prize-visual img { width: 100%; height: 100%; min-height: 220px; object-fit: cover; }
            .prize-placeholder { text-align: center; color: var(--dorado-claro); padding: 20px; }
            .prize-placeholder .icon { font-size: 64px; }
            .prize-placeholder strong { display: block; margin-top: 8px; font-size: 15px; }
            .participar { margin-top: 22px; }
            .how-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 15px; }
            .step {
                padding: 24px 20px;
                border-radius: 19px;
                background: white;
                border: 1px solid rgba(201,147,59,.18);
                box-shadow: 0 12px 35px rgba(0,0,0,.07);
            }
            .step-number { width: 38px; height: 38px; display: grid; place-items: center; border-radius: 50%; color: #1b1408; background: linear-gradient(135deg, #f0c56b, #b77925); font-weight: 900; }
            .step h3 { margin: 14px 0 7px; font-size: 17px; }
            .step p { margin: 0; color: var(--gris); font-size: 13px; line-height: 1.55; }
            .trust {
                display: grid;
                grid-template-columns: repeat(3,1fr);
                gap: 15px;
                margin-top: 18px;
            }
            .trust-card { padding: 20px; border-radius: 18px; background: #171717; color: white; border: 1px solid rgba(240,197,107,.14); }
            .trust-card strong { display: block; color: var(--dorado-claro); margin-bottom: 5px; }
            .trust-card p { margin: 0; color: rgba(255,255,255,.65); font-size: 13px; line-height: 1.5; }
            .winners {
                display: grid;
                grid-template-columns: repeat(3,1fr);
                gap: 16px;
            }
            .winner-card { padding: 22px; border-radius: 20px; background: white; border: 1px solid var(--borde); box-shadow: 0 12px 35px rgba(0,0,0,.07); }
            .winner-badge { color: #8d5e16; font-size: 11px; font-weight: 900; text-transform: uppercase; letter-spacing: 1px; }
            .winner-name { margin: 9px 0 4px; font-size: 21px; font-weight: 900; }
            .winner-prize { color: var(--gris); font-size: 13px; }
            .winner-number { margin-top: 16px; display: inline-block; padding: 7px 10px; border-radius: 9px; background: #f8f4eb; color: #8d5e16; font-weight: 900; }
            .empty { padding: 40px; text-align: center; border-radius: 20px; background: white; border: 1px solid var(--borde); color: var(--gris); }
            .instagram-box {
                display: flex;
                align-items: center;
                justify-content: space-between;
                gap: 20px;
                padding: 28px;
                border-radius: 24px;
                background: linear-gradient(135deg, #151515, #262018);
                color: white;
                border: 1px solid rgba(240,197,107,.18);
            }
            .instagram-box h2 { margin: 0 0 6px; }
            .instagram-box p { margin: 0; color: rgba(255,255,255,.65); }
            footer { padding: 35px 20px 45px; text-align: center; color: #777067; font-size: 13px; }
            footer img { width: 70px; height: 70px; object-fit: contain; margin-bottom: 7px; }
            footer a { color: #9a681f; font-weight: 900; text-decoration: none; }
            @media (max-width: 850px) {
                .nav-links { display: none; }
                .hero { grid-template-columns: 1fr; padding: 40px 25px; text-align: center; }
                .hero p { margin-left: auto; margin-right: auto; }
                .hero-actions { justify-content: center; }
                .sorteo-card { grid-template-columns: 1fr; }
                .prize-visual { order: -1; }
                .how-grid { grid-template-columns: repeat(2,1fr); }
                .winners, .trust { grid-template-columns: 1fr; }
            }
            @media (max-width: 520px) {
                .nav { padding: 9px 13px; }
                .brand img { width: 46px; height: 46px; }
                .brand-name { font-size: 18px; }
                .instagram { padding: 8px 10px; font-size: 11px; }
                .wrap { padding: 0 12px 45px; }
                .hero { margin-top: 14px; min-height: auto; border-radius: 25px; }
                .hero h1 { letter-spacing: -1.7px; }
                .hero-logo img { width: 270px; }
                .hero-logo:before { width: 290px; height: 290px; }
                .sorteo-card { padding: 23px 18px; }
                .card-head { flex-direction: column; }
                .how-grid { grid-template-columns: 1fr; }
                .btn-primary, .btn-secondary { width: 100%; }
                .instagram-box { flex-direction: column; align-items: flex-start; }
            }
        </style>
    </head>
    <body>
        <header class="topbar">
            <nav class="nav">
                <a class="brand" href="/">
                    <img src="{{ url_for('static', filename='logo.png') }}" alt="TA PREMIA'O">
                    <span class="brand-name">TA <span>PREMIA'O</span></span>
                </a>
                <div class="nav-links">
                    <a href="#sorteos">Sorteos</a>
                    <a href="#como-participar">Cómo participar</a>
                    <a href="#ganadores">Ganadores</a>
                </div>
                <a class="instagram" href="https://www.instagram.com/ta_premia_o/" target="_blank" rel="noopener">Instagram</a>
            </nav>
        </header>

        <main class="wrap">
            <section class="hero">
                <div>
                    <div class="eyebrow">✦ SORTEOS PROMOCIONALES</div>
                    <h1>Participa.<br><span>Gana.</span><br>Disfruta.</h1>
                    <p>
                        Bienvenido a <strong>TA PREMIA'O</strong>. Aquí encontrarás nuestros sorteos promocionales,
                        información clara y una forma sencilla de participar.
                    </p>
                    <div class="hero-actions">
                        <a class="btn-primary" href="#sorteos">Ver sorteos activos</a>
                        <a class="btn-secondary" href="#como-participar">¿Cómo participar?</a>
                    </div>
                </div>
                <div class="hero-logo">
                    <img src="{{ url_for('static', filename='logo.png') }}" alt="Logo oficial TA PREMIA'O">
                </div>
            </section>

            <section class="section" id="sorteos">
                <div class="section-head">
                    <div>
                        <div class="section-kicker">Oportunidades activas</div>
                        <h2>Participa en nuestros sorteos</h2>
                    </div>
                    <p class="section-intro">Participación gratuita y número automático.</p>
                </div>
                <div class="sorteos">
                    {% if sorteos %}
                        {% for sorteo in sorteos %}
                            <article class="sorteo-card">
                                <div>
                                    <div class="card-head">
                                        <h3>{{ sorteo["nombre"] }}</h3>
                                        <div class="active">● SORTEO ACTIVO</div>
                                    </div>
                                    <div class="prize-name">🏆 {{ sorteo["premio"] }}</div>
                                    <p class="description">{{ sorteo["descripcion"] or "Participa en este sorteo promocional." }}</p>
                                    <div class="details">
                                        <div class="detail">📅 <strong>Fecha:</strong> {{ sorteo["fecha"] }}</div>
                                        <div class="detail">🆓 100% gratuito</div>
                                        <div class="detail">🎟️ Número automático</div>
                                    </div>
                                    <a class="btn-primary participar" href="{{ url_for('participar', sorteo_id=sorteo['id']) }}">Participar</a>
                                </div>
                                <div class="prize-visual">
                                    {% if sorteo["premio_imagen"] %}
                                        <img src="{{ sorteo["premio_imagen"] }}" alt="Premio del sorteo">
                                    {% else %}
                                        <div class="prize-placeholder">
                                            <div class="icon">🎁</div>
                                            <strong>Imagen del premio</strong>
                                            <span>Se mostrará cuando la agregues.</span>
                                        </div>
                                    {% endif %}
                                </div>
                            </article>
                        {% endfor %}
                    {% else %}
                        <div class="empty">
                            <h3>No hay sorteos activos</h3>
                            <p>Vuelve pronto para conocer nuestro próximo sorteo.</p>
                        </div>
                    {% endif %}
                </div>
                <div class="trust">
                    <div class="trust-card"><strong>100% gratuito</strong><p>Participar no tiene costo.</p></div>
                    <div class="trust-card"><strong>Proceso sencillo</strong><p>Completa tus datos y recibe tu número.</p></div>
                    <div class="trust-card"><strong>Información clara</strong><p>Consulta premio, fecha y estado antes de participar.</p></div>
                </div>
            </section>

            <section class="section" id="como-participar">
                <div class="section-head">
                    <div>
                        <div class="section-kicker">Paso a paso</div>
                        <h2>¿Cómo participar?</h2>
                    </div>
                </div>
                <div class="how-grid">
                    <div class="step"><div class="step-number">1</div><h3>Elige un sorteo</h3><p>Revisa los sorteos activos y el premio disponible.</p></div>
                    <div class="step"><div class="step-number">2</div><h3>Completa tus datos</h3><p>Registra tu nombre, correo y teléfono.</p></div>
                    <div class="step"><div class="step-number">3</div><h3>Recibe tu número</h3><p>El sistema genera automáticamente tu número de participación.</p></div>
                    <div class="step"><div class="step-number">4</div><h3>Espera el sorteo</h3><p>Consulta la fecha y revisa los resultados publicados.</p></div>
                </div>
            </section>

            <section class="section" id="ganadores">
                <div class="section-head">
                    <div>
                        <div class="section-kicker">Resultados</div>
                        <h2>Ganadores</h2>
                    </div>
                    <p class="section-intro">Aquí publicaremos los ganadores de nuestros sorteos.</p>
                </div>
                {% if ganadores %}
                    <div class="winners">
                        {% for ganador in ganadores %}
                            <article class="winner-card">
                                <div class="winner-badge">🏆 Ganador</div>
                                <div class="winner-name">{{ ganador["ganador_nombre"] }}</div>
                                <div class="winner-prize">{{ ganador["premio"] }} · {{ ganador["sorteo_nombre"] }}</div>
                                <div class="winner-number">Número #{{ ganador["numero_ganador"] }}</div>
                            </article>
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="empty">
                        <h3>Próximamente</h3>
                        <p>Los ganadores de nuestros sorteos aparecerán aquí.</p>
                    </div>
                {% endif %}
            </section>

            <section class="section">
                <div class="instagram-box">
                    <div>
                        <h2>📸 Sigue a TA PREMIA'O</h2>
                        <p>Entérate de nuevos sorteos y publicaciones.</p>
                    </div>
                    <a class="btn-primary" href="https://www.instagram.com/ta_premia_o/" target="_blank" rel="noopener">@ta_premia_o</a>
                </div>
            </section>
        </main>

        <footer>
            <img src="{{ url_for('static', filename='logo.png') }}" alt="TA PREMIA'O">
            <div><strong>TA PREMIA'O</strong> · Sorteos promocionales</div>
            <div style="margin-top:7px;">Participación gratuita · <a href="https://www.instagram.com/ta_premia_o/" target="_blank" rel="noopener">Instagram</a></div>
        </footer>
    </body>
    </html>
    """

    return render_template_string(html, sorteos=sorteos, ganadores=ganadores)


# ==========================================
# PARTICIPAR
# ==========================================

@app.route("/participar/<int:sorteo_id>", methods=["GET", "POST"])
def participar(sorteo_id):

    conexion = conectar()

    sorteo = conexion.execute("""
        SELECT *
        FROM sorteos
        WHERE id = %s AND activo = 1
    """, (sorteo_id,)).fetchone()

    if not sorteo:
        conexion.close()
        return "Sorteo no encontrado."

    if request.method == "POST":

        nombre = request.form.get("nombre", "").strip()
        correo = request.form.get("correo", "").strip()
        telefono = request.form.get("telefono", "").strip()

        if not nombre or not correo or not telefono:
            conexion.close()

            return render_template_string("""
                <h2>Faltan datos</h2>
                <p>Debes completar todos los campos.</p>
                <a href="javascript:history.back()">Volver</a>
            """)

        # Evitar que el mismo correo se registre
        # dos veces en el mismo sorteo.
        existente = conexion.execute("""
            SELECT id
            FROM participantes
            WHERE correo = %s AND sorteo_id = %s
        """, (correo, sorteo_id)).fetchone()

        if existente:

            conexion.close()

            return render_template_string("""
                <h2>⚠️ Ya estás registrado</h2>

                <p>
                    Este correo ya participa en este sorteo.
                </p>

                <a href="/">Volver al inicio</a>
            """)

        cursor = conexion.cursor()

        cursor.execute("""
            INSERT INTO participantes
            (nombre, correo, telefono, sorteo_id)
            VALUES (%s, %s, %s, %s)
            RETURNING id
        """, (
            nombre,
            correo,
            telefono,
            sorteo_id
        ))

        numero = cursor.fetchone()["id"]

        conexion.commit()
        conexion.close()

        return render_template_string("""
            <!DOCTYPE html>

            <html lang="es">

            <head>
                <meta charset="UTF-8">

                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0">

                <title>Registro exitoso</title>

                <style>

                    body {
                        font-family: Arial;
                        background: #f4f6f8;
                        text-align: center;
                        padding: 50px;
                    }

                    .tarjeta {
                        background: white;
                        max-width: 500px;
                        margin: auto;
                        padding: 35px;
                        border-radius: 15px;
                        box-shadow: 0 5px 20px rgba(0,0,0,0.1);
                    }

                    .numero {
                        font-size: 50px;
                        font-weight: bold;
                        color: #2563eb;
                    }

                    a {
                        display: inline-block;
                        margin-top: 20px;
                        background: #2563eb;
                        color: white;
                        padding: 12px 20px;
                        border-radius: 8px;
                        text-decoration: none;
                    }

                </style>

            </head>

            <body>

                <div class="tarjeta">

                    <h1>✅ Registro exitoso</h1>

                    <p>Gracias por participar.</p>

                    <p>Tu número de participación es:</p>

                    <div class="numero">
                        #{{ numero }}
                    </div>

                    <a href="/">
                        Volver al inicio
                    </a>

                </div>

            </body>

            </html>
        """, numero=numero)

    conexion.close()

    html = """
    <!DOCTYPE html>

    <html lang="es">

    <head>

        <meta charset="UTF-8">

        <meta name="viewport"
              content="width=device-width, initial-scale=1.0">

        <title>Participar</title>

        <style>

            body {
                font-family: Arial;
                background: #f4f6f8;
                padding: 30px;
            }

            .tarjeta {
                max-width: 500px;
                margin: auto;
                background: white;
                padding: 30px;
                border-radius: 15px;
                box-shadow: 0 5px 20px rgba(0,0,0,0.08);
            }

            input {
                width: 100%;
                box-sizing: border-box;
                padding: 12px;
                margin: 8px 0 18px;
                border: 1px solid #ccc;
                border-radius: 8px;
                font-size: 16px;
            }

            button {
                width: 100%;
                padding: 14px;
                background: #2563eb;
                color: white;
                border: none;
                border-radius: 8px;
                font-size: 17px;
                cursor: pointer;
            }

        </style>

    </head>

    <body>

        <div class="tarjeta">

            <h1>🎁 {{ sorteo["nombre"] }}</h1>

            <h2>{{ sorteo["premio"] }}</h2>

            <p>
                {{ sorteo["descripcion"] }}
            </p>

            <hr>

            <h3>Datos del participante</h3>

            <form method="POST">

                <label>Nombre completo</label>

                <input
                    type="text"
                    name="nombre"
                    required
                >

                <label>Correo electrónico</label>

                <input
                    type="email"
                    name="correo"
                    required
                >

                <label>Teléfono</label>

                <input
                    type="tel"
                    name="telefono"
                    required
                >

                <button type="submit">
                    Participar
                </button>

            </form>

        </div>

    </body>

    </html>
    """

    return render_template_string(html, sorteo=sorteo)


# ==========================================
# LOGIN DEL ADMINISTRADOR
# ==========================================

@app.route("/login", methods=["GET", "POST"])
def login():

    if request.method == "POST":

        contrasena = request.form.get("contrasena", "")

        if contrasena == CONTRASENA_ADMIN:

            session["admin"] = True

            return redirect(url_for("admin"))

        return render_template_string("""
            <h2>Contraseña incorrecta</h2>
            <a href="/login">Intentar nuevamente</a>
        """)

    return render_template_string("""
        <!DOCTYPE html>

        <html lang="es">

        <head>
            <meta charset="UTF-8">
            <title>Administrador</title>

            <style>

                body {
                    font-family: Arial;
                    background: #f4f6f8;
                    padding: 50px;
                }

                .tarjeta {
                    background: white;
                    max-width: 400px;
                    margin: auto;
                    padding: 30px;
                    border-radius: 15px;
                }

                input {
                    width: 100%;
                    box-sizing: border-box;
                    padding: 12px;
                    margin: 10px 0;
                }

                button {
                    width: 100%;
                    padding: 12px;
                    background: #2563eb;
                    color: white;
                    border: none;
                    border-radius: 8px;
                }

            </style>

        </head>

        <body>

            <div class="tarjeta">

                <h2>🔐 Panel de administrador</h2>

                <form method="POST">

                    <input
                        type="password"
                        name="contrasena"
                        placeholder="Contraseña"
                        required
                    >

                    <button type="submit">
                        Entrar
                    </button>

                </form>

            </div>

        </body>

        </html>
    """)


# ==========================================
# PANEL ADMINISTRADOR
# ==========================================

@app.route("/admin")
@requiere_admin
def admin():

    conexion = conectar()

    sorteos = conexion.execute("""
        SELECT *
        FROM sorteos
        ORDER BY id DESC
    """).fetchall()

    participantes = conexion.execute("""
        SELECT
            participantes.*,
            sorteos.nombre AS sorteo_nombre
        FROM participantes
        LEFT JOIN sorteos
        ON participantes.sorteo_id = sorteos.id
        ORDER BY participantes.id DESC
    """).fetchall()

    conexion.close()

    html = """
    <!DOCTYPE html>

    <html lang="es">

    <head>

        <meta charset="UTF-8">

        <meta name="viewport"
              content="width=device-width, initial-scale=1.0">

        <title>Panel administrador</title>

        <style>

            body {
                font-family: Arial;
                background: #f4f6f8;
                margin: 0;
            }

            header {
                background: #111827;
                color: white;
                padding: 25px;
            }

            .contenedor {
                max-width: 1100px;
                margin: auto;
                padding: 30px;
            }

            .tarjeta {
                background: white;
                padding: 25px;
                margin-bottom: 25px;
                border-radius: 15px;
                box-shadow: 0 5px 20px rgba(0,0,0,0.08);
            }

            .boton {
                display: inline-block;
                padding: 10px 15px;
                background: #2563eb;
                color: white;
                text-decoration: none;
                border-radius: 8px;
                margin: 5px;
            }

            .verde {
                background: #16a34a;
            }

            .rojo {
                background: #dc2626;
            }

            table {
                width: 100%;
                border-collapse: collapse;
            }

            th, td {
                padding: 10px;
                border-bottom: 1px solid #ddd;
                text-align: left;
            }

        </style>

    </head>

    <body>

        <header>

            <h1>🔐 Panel de administrador</h1>

            <a class="boton rojo"
               href="/logout">
                Cerrar sesión
            </a>

        </header>

        <div class="contenedor">

            <div class="tarjeta">

                <h2>🎁 Sorteos</h2>

                <a class="boton verde"
                   href="/crear-sorteo">
                    ➕ Crear nuevo sorteo
                </a>

                {% for sorteo in sorteos %}

                    <hr>

                    <h3>
                        {{ sorteo["nombre"] }}
                    </h3>

                    <p>
                        🎁 {{ sorteo["premio"] }}
                    </p>

                    <p>
                        📅 {{ sorteo["fecha"] }}
                    </p>

                    <p>
                        Estado:
                        {% if sorteo["activo"] %}
                            🟢 Activo
                        {% else %}
                            🔴 Inactivo
                        {% endif %}
                    </p>

                    <a class="boton"
                       href="/ganador/{{ sorteo['id'] }}">
                        🎉 Elegir ganador
                    </a>

                {% endfor %}

            </div>


            <div class="tarjeta">

                <h2>👥 Participantes</h2>

                <table>

                    <tr>
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Correo</th>
                        <th>Teléfono</th>
                        <th>Sorteo</th>
                    </tr>

                    {% for participante in participantes %}

                    <tr>

                        <td>
                            {{ participante["id"] }}
                        </td>

                        <td>
                            {{ participante["nombre"] }}
                        </td>

                        <td>
                            {{ participante["correo"] }}
                        </td>

                        <td>
                            {{ participante["telefono"] }}
                        </td>

                        <td>
                            {{ participante["sorteo_nombre"] or "—" }}
                        </td>

                    </tr>

                    {% endfor %}

                </table>

            </div>

        </div>

    </body>

    </html>
    """

    return render_template_string(
        html,
        sorteos=sorteos,
        participantes=participantes
    )


# ==========================================
# CREAR SORTEO
# ==========================================

@app.route("/crear-sorteo", methods=["GET", "POST"])
@requiere_admin
def crear_sorteo():

    if request.method == "POST":
        nombre = request.form.get("nombre", "").strip()
        premio = request.form.get("premio", "").strip()
        descripcion = request.form.get("descripcion", "").strip()
        fecha = request.form.get("fecha", "").strip()
        premio_imagen = request.form.get("premio_imagen", "").strip()

        if not nombre or not premio or not fecha:
            return "<h2>Faltan datos</h2><p>Nombre, premio y fecha son obligatorios.</p><a href='/crear-sorteo'>Volver</a>"

        conexion = conectar()
        conexion.execute("""
            INSERT INTO sorteos
            (nombre, premio, descripcion, fecha, activo, premio_imagen)
            VALUES (%s, %s, %s, %s, 1, %s)
        """, (nombre, premio, descripcion, fecha, premio_imagen or None))
        conexion.commit()
        conexion.close()
        return redirect(url_for("admin"))

    return render_template_string("""
    <!DOCTYPE html>
    <html lang="es"><head>
        <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Crear sorteo | TA PREMIA'O</title>
        <style>
            body{margin:0;font-family:Arial,sans-serif;background:#f7f2e9;color:#17130d;padding:25px}
            .card{max-width:650px;margin:30px auto;background:#fff;padding:32px;border-radius:22px;border:1px solid rgba(201,147,59,.25);box-shadow:0 18px 50px rgba(0,0,0,.1)}
            img{display:block;width:90px;height:90px;object-fit:contain;margin:0 auto 12px}
            h1{text-align:center}.sub{text-align:center;color:#6f6b63;margin-bottom:28px}
            label{display:block;font-weight:800;margin:16px 0 7px}input,textarea{width:100%;box-sizing:border-box;padding:13px;border:1px solid #d8d0c2;border-radius:10px;font-size:15px}
            button{width:100%;margin-top:22px;padding:14px;border:0;border-radius:11px;background:#bd8330;color:#fff;font-weight:900;font-size:16px;cursor:pointer}
            .back{display:block;text-align:center;margin-top:18px;color:#8d5e16;text-decoration:none;font-weight:800}
        </style>
    </head><body>
        <div class="card">
            <img src="{{ url_for('static', filename='logo.png') }}" alt="TA PREMIA'O">
            <h1>Crear nuevo sorteo</h1><p class="sub">Completa la información que verá el público.</p>
            <form method="POST">
                <label>Nombre del sorteo</label><input type="text" name="nombre" required>
                <label>Premio</label><input type="text" name="premio" required>
                <label>Descripción</label><textarea name="descripcion" rows="4"></textarea>
                <label>Fecha del sorteo</label><input type="date" name="fecha" required>
                <label>Imagen del premio (opcional)</label><input type="url" name="premio_imagen" placeholder="https://...">
                <button type="submit">Crear sorteo</button>
            </form>
            <a class="back" href="/admin">← Volver al administrador</a>
        </div>
    </body></html>
    """)


# ==========================================
# ELEGIR GANADOR
# ==========================================

@app.route("/ganador/<int:sorteo_id>")
@requiere_admin
def ganador(sorteo_id):

    conexion = conectar()
    sorteo = conexion.execute("SELECT * FROM sorteos WHERE id = %s", (sorteo_id,)).fetchone()

    if not sorteo:
        conexion.close()
        return "Sorteo no encontrado."

    ganador_existente = conexion.execute("""
        SELECT g.id, g.fecha, p.id AS numero, p.nombre
        FROM ganadores g
        JOIN participantes p ON p.id = g.participante_id
        WHERE g.sorteo_id = %s
    """, (sorteo_id,)).fetchone()

    if ganador_existente:
        ganador_data = ganador_existente
        ya_existia = True
    else:
        participantes = conexion.execute("SELECT * FROM participantes WHERE sorteo_id = %s", (sorteo_id,)).fetchall()
        if not participantes:
            conexion.close()
            return render_template_string("""
                <div style="font-family:Arial;max-width:520px;margin:60px auto;text-align:center">
                    <h2>⚠️ No hay participantes</h2><p>Todavía no hay participantes en este sorteo.</p>
                    <a href="/admin">Volver al panel</a>
                </div>
            """)
        elegido = random.choice(participantes)
        cursor = conexion.cursor()
        cursor.execute("""
            INSERT INTO ganadores (sorteo_id, participante_id)
            VALUES (%s, %s)
            ON CONFLICT (sorteo_id) DO NOTHING
            RETURNING id
        """, (sorteo_id, elegido["id"]))
        fila = cursor.fetchone()
        if fila is None:
            ganador_data = conexion.execute("""
                SELECT g.id, g.fecha, p.id AS numero, p.nombre
                FROM ganadores g JOIN participantes p ON p.id = g.participante_id
                WHERE g.sorteo_id = %s
            """, (sorteo_id,)).fetchone()
        else:
            ganador_data = conexion.execute("""
                SELECT g.id, g.fecha, p.id AS numero, p.nombre
                FROM ganadores g JOIN participantes p ON p.id = g.participante_id
                WHERE g.sorteo_id = %s
            """, (sorteo_id,)).fetchone()
        conexion.commit()
        ya_existia = False

    conexion.close()

    return render_template_string("""
    <!DOCTYPE html><html lang="es"><head>
        <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Ganador | TA PREMIA'O</title>
        <style>
            body{margin:0;font-family:Arial,sans-serif;background:linear-gradient(135deg,#090909,#2b2114);color:#fff;padding:30px}
            .card{max-width:620px;margin:50px auto;background:#fff;color:#17130d;padding:42px;border-radius:26px;text-align:center;box-shadow:0 25px 70px rgba(0,0,0,.35)}
            img{width:100px;height:100px;object-fit:contain}.badge{display:inline-block;margin:12px 0;padding:8px 13px;border-radius:999px;background:#f8edd5;color:#8d5e16;font-weight:900;font-size:12px}
            .name{font-size:34px;font-weight:900;margin:14px 0}.number{font-size:54px;color:#b77925;font-weight:900}.prize{font-size:18px;color:#6f6b63}
            a{display:inline-block;margin-top:25px;padding:12px 20px;border-radius:10px;background:#bd8330;color:#fff;text-decoration:none;font-weight:900}
        </style></head><body><div class="card">
        <img src="{{ url_for('static', filename='logo.png') }}" alt="TA PREMIA'O">
        <div class="badge">🏆 {% if ya_existia %}GANADOR PUBLICADO{% else %}GANADOR SELECCIONADO{% endif %}</div>
        <h1>{{ sorteo["nombre"] }}</h1><p class="prize">Premio: <strong>{{ sorteo["premio"] }}</strong></p>
        <div class="name">{{ ganador_data["nombre"] }}</div><div class="number">#{{ ganador_data["numero"] }}</div>
        <p>Este resultado queda registrado para este sorteo.</p><a href="/admin">Volver al panel</a>
    </div></body></html>
    """, sorteo=sorteo, ganador_data=ganador_data, ya_existia=ya_existia)


# ==========================================
# CERRAR SESIÓN
# ==========================================

@app.route("/logout")
def logout():

    session.clear()

    return redirect(url_for("inicio"))


# ==========================================
# INICIAR PROGRAMA
# ==========================================

crear_base_datos()


if __name__ == "__main__":

    app.run(
        host="0.0.0.0",
        port=int(os.environ.get("PORT", 5000)),
        debug=False
    )