from flask import Flask, request, redirect, url_for, session, render_template_string
import os
import psycopg
from psycopg.rows import dict_row
import random
import base64
import mimetypes
from functools import wraps

app = Flask(__name__, static_folder="static", static_url_path="/static")
app.secret_key = os.environ.get("FLASK_SECRET_KEY", "clave-demo-sorteoweb")
CONTRASENA_ADMIN = os.environ.get("ADMIN_PASSWORD", "1234")
DATABASE_URL = os.environ.get("DATABASE_URL")


def conectar():
    if not DATABASE_URL:
        raise RuntimeError("Falta la variable de entorno DATABASE_URL.")
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def archivo_a_data_url(archivo, max_mb=5):
    if not archivo or not archivo.filename:
        return None
    data = archivo.read()
    if len(data) > max_mb * 1024 * 1024:
        raise ValueError(f"La imagen no puede superar {max_mb} MB.")
    tipo = archivo.mimetype or mimetypes.guess_type(archivo.filename)[0] or "application/octet-stream"
    if not tipo.startswith("image/"):
        raise ValueError("El archivo debe ser una imagen.")
    return f"data:{tipo};base64," + base64.b64encode(data).decode("ascii")


def crear_base_datos():
    conexion = conectar()
    cur = conexion.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS sorteos (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre TEXT NOT NULL,
            premio TEXT NOT NULL,
            descripcion TEXT,
            fecha TEXT,
            activo INTEGER DEFAULT 1
        )
    """)
    cur.execute("""
        CREATE TABLE IF NOT EXISTS participantes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre TEXT NOT NULL,
            correo TEXT NOT NULL,
            telefono TEXT NOT NULL,
            sorteo_id BIGINT REFERENCES sorteos(id)
        )
    """)
    cur.execute("ALTER TABLE sorteos ADD COLUMN IF NOT EXISTS imagen_premio TEXT")
    cur.execute("ALTER TABLE sorteos ADD COLUMN IF NOT EXISTS ganador_id BIGINT")
    cur.execute("""
        CREATE TABLE IF NOT EXISTS configuracion (
            id INTEGER PRIMARY KEY,
            logo_data TEXT,
            instagram TEXT DEFAULT '@ta_premia_o',
            titulo TEXT DEFAULT '¡Participa y podrías ganar!',
            subtitulo TEXT DEFAULT 'Regístrate en nuestros sorteos promocionales y descubre si eres el próximo ganador.',
            badge TEXT DEFAULT '🏆 GRAN SORTEO PROMOCIONAL'
        )
    """)
    cur.execute("SELECT id FROM configuracion WHERE id=1")
    if not cur.fetchone():
        cur.execute("INSERT INTO configuracion (id) VALUES (1)")
    cur.execute("SELECT COUNT(*) AS cantidad FROM sorteos")
    if cur.fetchone()["cantidad"] == 0:
        cur.execute("""
            INSERT INTO sorteos (nombre,premio,descripcion,fecha,activo)
            VALUES (%s,%s,%s,%s,1)
        """, ("Gran Sorteo Promocional", "Premio sorpresa", "Participa en nuestro sorteo promocional.", "2026-12-31"))
    conexion.commit()
    cur.close()
    conexion.close()


def requiere_admin(funcion):
    @wraps(funcion)
    def protegida(*args, **kwargs):
        if not session.get("admin"):
            return redirect(url_for("login"))
        return funcion(*args, **kwargs)
    return protegida


BASE_STYLE = """
*{box-sizing:border-box} body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#f5f5f3;color:#171717} a{text-decoration:none}.wrap{max-width:1180px;margin:auto;padding:0 20px}.top{background:#111;color:#fff;border-bottom:3px solid #b98935}.topin{display:flex;align-items:center;justify-content:space-between;padding:16px 20px;max-width:1180px;margin:auto}.brand{display:flex;align-items:center;gap:12px;font-weight:900;font-size:24px}.brand img{width:54px;height:54px;border-radius:50%;object-fit:cover;background:#fff}.brand span{color:#d5a64b}.btn{display:inline-block;border:0;border-radius:10px;padding:12px 17px;font-weight:800;cursor:pointer}.gold{background:#c99a3b;color:#111}.dark{background:#171717;color:#fff}.white{background:#fff;color:#111;border:1px solid #ddd}.card{background:#fff;border:1px solid #e5e5e2;border-radius:18px;padding:24px;box-shadow:0 10px 28px rgba(0,0,0,.07)}.grid{display:grid;gap:18px}.two{grid-template-columns:1fr 1fr}.three{grid-template-columns:repeat(3,1fr)}label{display:block;font-weight:800;margin:0 0 7px}input,textarea,select{width:100%;padding:12px;border:1px solid #d7d7d2;border-radius:10px;font:inherit;margin-bottom:15px}textarea{min-height:110px;resize:vertical}.muted{color:#707070}.pill{display:inline-block;border-radius:999px;padding:6px 10px;font-size:12px;font-weight:800}.on{background:#e6f6ea;color:#17763b}.off{background:#f8e6e6;color:#a52b2b}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px;border-bottom:1px solid #eee;white-space:nowrap}.hero{background:#111;color:#fff;padding:46px 0}.hero h1{font-size:clamp(38px,6vw,68px);margin:10px 0;color:#fff}.hero h1 span{color:#d5a64b}.hero p{font-size:18px;line-height:1.6;color:#ddd;max-width:680px}.logohero{width:220px;height:220px;border-radius:50%;object-fit:cover;border:5px solid #d5a64b;background:#fff}.publiccard{margin-top:-28px;position:relative}.prizeimg{width:100%;max-height:330px;object-fit:cover;border-radius:14px;background:#f4f4f0}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:25px 0}.step{padding:22px;background:#fff;border-radius:16px;border-top:4px solid #c99a3b}.footer{padding:35px 20px;text-align:center;color:#777}.actions{display:flex;gap:9px;flex-wrap:wrap}.notice{padding:12px 15px;border-radius:10px;background:#fff5d9;color:#765400;margin-bottom:16px}.adminnav{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}@media(max-width:760px){.two,.three,.steps{grid-template-columns:1fr}.topin{padding:12px 15px}.brand{font-size:18px}.brand img{width:44px;height:44px}.hero{text-align:center;padding:35px 0}.logohero{width:170px;height:170px;margin-top:25px}.publiccard{margin-top:15px}.wrap{padding:0 13px}}
"""


@app.route("/")
def inicio():
    conexion = conectar()
    sorteos = conexion.execute("SELECT * FROM sorteos WHERE activo=1 ORDER BY id DESC").fetchall()
    config = conexion.execute("SELECT * FROM configuracion WHERE id=1").fetchone()
    conexion.close()
    logo = config["logo_data"] if config and config["logo_data"] else url_for("static", filename="logo.png")
    return render_template_string("""
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TA PREMIA'O</title><style>{{style}}</style></head><body>
<header class="top"><div class="topin"><div class="brand"><img src="{{logo}}"><div>TA <span>PREMIA'O</span></div></div><a class="btn gold" href="#sorteos">Participar</a></div></header>
<section class="hero"><div class="wrap"><div class="grid two" style="align-items:center"><div><div class="pill" style="background:#2a2a2a;color:#d5a64b">{{config['badge']}}</div><h1>{{config['titulo']}}</h1><p>{{config['subtitulo']}}</p></div><div style="text-align:center"><img class="logohero" src="{{logo}}"></div></div></div></section>
<main class="wrap" id="sorteos"><div class="grid" style="margin-top:28px">{% for s in sorteos %}<article class="card publiccard"><div class="actions" style="justify-content:space-between"><span class="pill on">● SORTEO ACTIVO</span><span class="pill" style="background:#f4ead3;color:#765400">📅 {{s['fecha']}}</span></div><h2 style="font-size:30px;margin:14px 0 6px">{{s['nombre']}}</h2><div style="font-size:22px;font-weight:900;color:#9a6d18;margin-bottom:15px">🎁 {{s['premio']}}</div>{% if s['imagen_premio'] %}<img class="prizeimg" src="{{s['imagen_premio']}}" alt="Imagen del premio">{% endif %}<p class="muted" style="line-height:1.6">{{s['descripcion']}}</p><a class="btn dark" style="margin-top:10px" href="{{url_for('participar',sorteo_id=s['id'])}}">Participar</a></article>{% else %}<div class="card"><h2>No hay sorteos activos</h2><p class="muted">Vuelve pronto.</p></div>{% endfor %}</div>
<section><h2 style="font-size:30px;margin-top:42px">¿Cómo participar?</h2><div class="steps"><div class="step"><b>1. Elige el sorteo</b><p class="muted">Selecciona el sorteo activo que quieras.</p></div><div class="step"><b>2. Completa tus datos</b><p class="muted">Registra tus datos en el formulario.</p></div><div class="step"><b>3. Recibe tu número</b><p class="muted">Obtendrás automáticamente tu número de participación.</p></div></div></section>
<section><h2 style="font-size:30px;margin-top:35px">🏆 Ganadores</h2><div class="card">{% for s in sorteos if s['ganador_id'] %}{% set g=ganadores.get(s['ganador_id']) %}{% if g %}<p><b>{{s['nombre']}}</b> — {{g['nombre']}} · #{{g['id']}}</p>{% endif %}{% else %}<p class="muted">Los ganadores aparecerán aquí después de realizar los sorteos.</p>{% endfor %}</div></section>
</main><footer class="footer">TA PREMIA'O · Sorteos promocionales · <a href="https://www.instagram.com/{{config['instagram'].lstrip('@')}}/" target="_blank">📸 {{config['instagram']}}</a></footer></body></html>
""", style=BASE_STYLE, sorteos=sorteos, config=config, logo=logo, ganadores=_ganadores_para(sorteos))


def _ganadores_para(sorteos):
    ids=[s["ganador_id"] for s in sorteos if s.get("ganador_id")]
    if not ids:return {}
    c=conectar(); rows=c.execute("SELECT * FROM participantes WHERE id = ANY(%s)",(ids,)).fetchall(); c.close(); return {r["id"]:r for r in rows}


@app.route("/participar/<int:sorteo_id>", methods=["GET","POST"])
def participar(sorteo_id):
    c=conectar(); s=c.execute("SELECT * FROM sorteos WHERE id=%s AND activo=1",(sorteo_id,)).fetchone()
    if not s:c.close(); return "Sorteo no encontrado.",404
    if request.method=="POST":
        nombre=request.form.get("nombre","").strip(); correo=request.form.get("correo","").strip(); telefono=request.form.get("telefono","").strip()
        if not nombre or not correo or not telefono:c.close(); return "Completa todos los campos.",400
        if c.execute("SELECT id FROM participantes WHERE correo=%s AND sorteo_id=%s",(correo,sorteo_id)).fetchone():c.close(); return "Este correo ya está registrado en este sorteo.",409
        cur=c.cursor(); cur.execute("INSERT INTO participantes(nombre,correo,telefono,sorteo_id) VALUES(%s,%s,%s,%s) RETURNING id",(nombre,correo,telefono,sorteo_id)); numero=cur.fetchone()["id"]; c.commit(); c.close()
        return render_template_string("""<!doctype html><html lang=es><head><meta name=viewport content='width=device-width,initial-scale=1'><title>Registro</title><style>{{style}}</style></head><body><div class=wrap style='padding-top:50px'><div class=card style='max-width:520px;margin:auto;text-align:center'><h1>✅ Registro exitoso</h1><p>Tu número de participación es</p><div style='font-size:60px;font-weight:900;color:#b8872d'>#{{numero}}</div><a class='btn dark' href='/'>Volver al inicio</a></div></div></body></html>""",style=BASE_STYLE,numero=numero)
    c.close()
    return render_template_string("""<!doctype html><html lang=es><head><meta name=viewport content='width=device-width,initial-scale=1'><title>Participar</title><style>{{style}}</style></head><body><div class=wrap style='padding:40px 15px'><div class=card style='max-width:560px;margin:auto'><h1>{{s['nombre']}}</h1><h2>{{s['premio']}}</h2>{% if s['imagen_premio'] %}<img class=prizeimg src='{{s['imagen_premio']}}'>{% endif %}<p class=muted>{{s['descripcion']}}</p><form method=post><label>Nombre completo</label><input name=nombre required><label>Correo electrónico</label><input type=email name=correo required><label>Teléfono</label><input name=telefono required><button class='btn dark' style='width:100%'>Participar</button></form></div></div></body></html>""",style=BASE_STYLE,s=s)


@app.route("/login",methods=["GET","POST"])
def login():
    if request.method=="POST":
        if request.form.get("contrasena","")==CONTRASENA_ADMIN:session["admin"]=True; return redirect(url_for("admin"))
        return "Contraseña incorrecta. <a href='/login'>Intentar nuevamente</a>"
    return render_template_string("""<!doctype html><html lang=es><head><meta name=viewport content='width=device-width,initial-scale=1'><title>Admin</title><style>{{style}}</style></head><body><div class=wrap style='padding-top:70px'><div class=card style='max-width:420px;margin:auto'><h1>🔐 Administrador</h1><form method=post><label>Contraseña</label><input type=password name=contrasena required><button class='btn dark' style='width:100%'>Entrar</button></form></div></div></body></html>""",style=BASE_STYLE)


@app.route("/admin")
@requiere_admin
def admin():
    c=conectar(); sorteos=c.execute("SELECT * FROM sorteos ORDER BY id DESC").fetchall(); participantes=c.execute("SELECT participantes.*,sorteos.nombre AS sorteo_nombre FROM participantes LEFT JOIN sorteos ON participantes.sorteo_id=sorteos.id ORDER BY participantes.id DESC").fetchall(); config=c.execute("SELECT * FROM configuracion WHERE id=1").fetchone(); c.close()
    logo=config["logo_data"] if config and config["logo_data"] else url_for("static",filename="logo.png")
    return render_template_string("""<!doctype html><html lang=es><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><title>Admin TA PREMIA'O</title><style>{{style}}</style></head><body><header class=top><div class=topin><div class=brand><img src='{{logo}}'><div>TA <span>PREMIA'O</span></div></div><a class='btn white' href='/logout'>Cerrar sesión</a></div></header><main class=wrap><div class=adminnav><a class='btn gold' href='#config'>⚙️ Página</a><a class='btn dark' href='#sorteos'>🎯 Sorteos</a><a class='btn white' href='#participantes'>👥 Participantes</a></div><div class=card id=config><h2>🎨 Editar página</h2><p class=muted>Todo lo que cambies aquí se guarda en Supabase. No necesitas comandos.</p><form method=post action='/admin/configuracion' enctype='multipart/form-data'><div class=grid two><div><label>Logo</label><input type=file name=logo accept='image/*'><small class=muted>Si no eliges uno, se mantiene el actual.</small></div><div><label>Instagram</label><input name=instagram value='{{config["instagram"]}}' placeholder='@ta_premia_o'></div></div><label>Título principal</label><input name=titulo value='{{config["titulo"]}}'><label>Subtítulo</label><textarea name=subtitulo>{{config["subtitulo"]}}</textarea><label>Texto de la insignia</label><input name=badge value='{{config["badge"]}}'><button class='btn gold'>💾 Guardar cambios de página</button></form></div><div id=sorteos style='margin-top:22px' class=card><div class=actions style='justify-content:space-between'><h2>🎯 Sorteos</h2><a class='btn gold' href='/crear-sorteo'>➕ Crear sorteo</a></div>{% for s in sorteos %}<div style='border-top:1px solid #eee;padding:18px 0'><div class=actions style='justify-content:space-between'><div><h3 style='margin:0'>{{s['nombre']}}</h3><p class=muted>🎁 {{s['premio']}} · 📅 {{s['fecha']}}</p></div><span class='pill {{"on" if s["activo"] else "off"}}'>{{"Activo" if s["activo"] else "Inactivo"}}</span></div><div class=actions style='margin-top:10px'><a class='btn dark' href='/admin/editar-sorteo/{{s["id"]}}'>✏️ Editar</a><a class='btn white' href='/ganador/{{s["id"]}}'>🏆 {{"Ver ganador" if s['ganador_id'] else "Elegir ganador"}}</a></div></div>{% endfor %}</div><div id=participantes style='margin:22px 0' class=card><h2>👥 Participantes</h2><div class=tablewrap><table><tr><th>#</th><th>Nombre</th><th>Correo</th><th>Teléfono</th><th>Sorteo</th></tr>{% for p in participantes %}<tr><td>{{p['id']}}</td><td>{{p['nombre']}}</td><td>{{p['correo']}}</td><td>{{p['telefono']}}</td><td>{{p['sorteo_nombre'] or '—'}}</td></tr>{% endfor %}</table></div></div></main></body></html>""",style=BASE_STYLE,sorteos=sorteos,participantes=participantes,config=config,logo=logo)


@app.route("/admin/configuracion",methods=["POST"])
@requiere_admin
def guardar_configuracion():
    instagram=request.form.get("instagram","@ta_premia_o").strip() or "@ta_premia_o"
    titulo=request.form.get("titulo","").strip(); subtitulo=request.form.get("subtitulo","").strip(); badge=request.form.get("badge","").strip()
    logo=None
    try: logo=archivo_a_data_url(request.files.get("logo"),3)
    except ValueError as e: return str(e),400
    c=conectar()
    if logo:
        c.execute("UPDATE configuracion SET logo_data=%s,instagram=%s,titulo=%s,subtitulo=%s,badge=%s WHERE id=1",(logo,instagram,titulo,subtitulo,badge))
    else:
        c.execute("UPDATE configuracion SET instagram=%s,titulo=%s,subtitulo=%s,badge=%s WHERE id=1",(instagram,titulo,subtitulo,badge))
    c.commit(); c.close(); return redirect(url_for("admin"))


@app.route("/admin/editar-sorteo/<int:sorteo_id>",methods=["GET","POST"])
@requiere_admin
def editar_sorteo(sorteo_id):
    c=conectar(); s=c.execute("SELECT * FROM sorteos WHERE id=%s",(sorteo_id,)).fetchone()
    if not s:c.close(); return "Sorteo no encontrado.",404
    if request.method=="POST":
        nombre=request.form.get("nombre","").strip(); premio=request.form.get("premio","").strip(); descripcion=request.form.get("descripcion","").strip(); fecha=request.form.get("fecha","").strip(); activo=1 if request.form.get("activo")=="1" else 0
        borrar=request.form.get("borrar_imagen")=="1"
        try: imagen=archivo_a_data_url(request.files.get("imagen_premio"),5)
        except ValueError as e:c.close(); return str(e),400
        if imagen is not None: c.execute("UPDATE sorteos SET nombre=%s,premio=%s,descripcion=%s,fecha=%s,activo=%s,imagen_premio=%s WHERE id=%s",(nombre,premio,descripcion,fecha,activo,imagen,sorteo_id))
        elif borrar: c.execute("UPDATE sorteos SET nombre=%s,premio=%s,descripcion=%s,fecha=%s,activo=%s,imagen_premio=NULL WHERE id=%s",(nombre,premio,descripcion,fecha,activo,sorteo_id))
        else:c.execute("UPDATE sorteos SET nombre=%s,premio=%s,descripcion=%s,fecha=%s,activo=%s WHERE id=%s",(nombre,premio,descripcion,fecha,activo,sorteo_id))
        c.commit(); c.close(); return redirect(url_for("admin"))
    c.close()
    return render_template_string("""<!doctype html><html lang=es><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><title>Editar sorteo</title><style>{{style}}</style></head><body><div class=wrap style='padding:35px 15px'><div class=card style='max-width:700px;margin:auto'><div class=actions style='justify-content:space-between'><h1>✏️ Editar sorteo</h1><a class='btn white' href='/admin'>← Volver</a></div><form method=post enctype='multipart/form-data'><label>Nombre</label><input name=nombre value='{{s["nombre"]}}' required><label>Premio</label><input name=premio value='{{s["premio"]}}' required><label>Imagen del premio</label>{% if s['imagen_premio'] %}<img class=prizeimg style='max-height:220px;margin-bottom:12px' src='{{s["imagen_premio"]}}'>{% endif %}<input type=file name=imagen_premio accept='image/*'><label>Descripción</label><textarea name=descripcion>{{s['descripcion'] or ''}}</textarea><label>Fecha</label><input type=date name=fecha value='{{s["fecha"]}}' required><label>Estado</label><select name=activo><option value=1 {{'selected' if s['activo'] else ''}}>Activo</option><option value=0 {{'selected' if not s['activo'] else ''}}>Inactivo</option></select>{% if s['imagen_premio'] %}<label><input type=checkbox name=borrar_imagen value=1 style='width:auto'> Eliminar imagen actual si no subes otra</label>{% endif %}<button class='btn gold'>💾 Guardar cambios</button></form></div></div></body></html>""",style=BASE_STYLE,s=s)


@app.route("/crear-sorteo",methods=["GET","POST"])
@requiere_admin
def crear_sorteo():
    if request.method=="POST":
        nombre=request.form.get("nombre","").strip(); premio=request.form.get("premio","").strip(); descripcion=request.form.get("descripcion","").strip(); fecha=request.form.get("fecha","").strip()
        if not nombre or not premio or not fecha:return "Nombre, premio y fecha son obligatorios.",400
        try: imagen=archivo_a_data_url(request.files.get("imagen_premio"),5)
        except ValueError as e:return str(e),400
        c=conectar(); c.execute("INSERT INTO sorteos(nombre,premio,descripcion,fecha,activo,imagen_premio) VALUES(%s,%s,%s,%s,1,%s)",(nombre,premio,descripcion,fecha,imagen)); c.commit(); c.close(); return redirect(url_for("admin"))
    return render_template_string("""<!doctype html><html lang=es><head><meta name=viewport content='width=device-width,initial-scale=1'><title>Crear sorteo</title><style>{{style}}</style></head><body><div class=wrap style='padding:35px 15px'><div class=card style='max-width:700px;margin:auto'><h1>➕ Crear sorteo</h1><form method=post enctype='multipart/form-data'><label>Nombre</label><input name=nombre required><label>Premio</label><input name=premio required><label>Imagen del premio</label><input type=file name=imagen_premio accept='image/*'><label>Descripción</label><textarea name=descripcion></textarea><label>Fecha</label><input type=date name=fecha required><button class='btn gold'>Crear sorteo</button></form></div></div></body></html>""",style=BASE_STYLE)


@app.route("/ganador/<int:sorteo_id>")
@requiere_admin
def ganador(sorteo_id):
    c=conectar(); s=c.execute("SELECT * FROM sorteos WHERE id=%s",(sorteo_id,)).fetchone()
    if not s:c.close(); return "Sorteo no encontrado.",404
    if s["ganador_id"]:
        g=c.execute("SELECT * FROM participantes WHERE id=%s",(s["ganador_id"],)).fetchone()
    else:
        ps=c.execute("SELECT * FROM participantes WHERE sorteo_id=%s",(sorteo_id,)).fetchall(); g=random.choice(ps) if ps else None
        if g:c.execute("UPDATE sorteos SET ganador_id=%s WHERE id=%s",(g["id"],sorteo_id)); c.commit()
    c.close()
    if not g:return "<h2>No hay participantes.</h2><a href='/admin'>Volver</a>"
    return render_template_string("""<!doctype html><html lang=es><head><meta name=viewport content='width=device-width,initial-scale=1'><title>Ganador</title><style>{{style}}</style></head><body><div class=wrap style='padding:60px 15px'><div class=card style='max-width:620px;margin:auto;text-align:center'><h1>🏆 Ganador</h1><h2>{{s['nombre']}}</h2><p>Premio: <b>{{s['premio']}}</b></p><div style='font-size:48px;font-weight:900;color:#b8872d'>{{g['nombre']}}</div><p>Número #{{g['id']}}</p><a class='btn dark' href='/admin'>Volver al panel</a></div></div></body></html>""",style=BASE_STYLE,s=s,g=g)


@app.route("/logout")
def logout():session.clear(); return redirect(url_for("inicio"))

crear_base_datos()

if __name__=="__main__":
    app.run(host="0.0.0.0",port=int(os.environ.get("PORT",5000)),debug=False)
